# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &users:
    - &admin_user1 DEAD BEEF 7777 6666 5555 4444 3333 2222 1111 0000 AAAA
  - &hosts:
    - &server_host1 agelaldkfjasklvjasdklvjaskljflaskdjflkdsajflkajflkjakfdjak
    - &server_host2 agelaldkfjasklvjasdklvjaskljflaskdjflkdsajflkajflkjakfdjak
    - &server_host3 agelaldkfjasklvjasdklvjaskljflaskdjflkdsajflkajflkjakfdjak
    - &server_host4 agelaldkfjasklvjasdklvjaskljflaskdjflkdsajflkajflkjakfdjak


creation_rules:
  - path_regex: nix/secrets.ya?ml$
    key_groups:
    - pgp:
      - *admin_user1
      age:
      - *server_host1
      - *server_host2
      - *server_host3
      - *server_host4
